As a health department employee I want that e-mail sending is asynchronous and repeated in case of errors so that I will get my notification when new data is received
iris-connect/iris-client pull request #207
Opened 2021-07-08 14:45 UTC by SWlionmint

The current implementation provides a return value of the Try type that allows for individual error handling. We now want to capsule this further to allow the email sending to be done asynchronous.

As part of this we also want that emails that have failed are send again until they either succeed or they have been send multiple times. Each time a sending fails this should be tracked and when it fails completely it should be logged with a higher priority.

The data of a failed email should be available for inspection to identify errors.

- For reviews I am hoping that we do not need to save the data of the failed emails and instead can work with the log only. As such ideas what is needed in the log and if what we have is already enough would be great.

2021-07-12 10:50 UTC, tboegner requested changes
Currently the email sending code is not triggered, when data arrives, because it is called in `Event|CaseDataRequestController.update()` (called at changes from Frontend).
IMHO we should have a possibility to deactive the email sending (with default deactivated). With the current configuration all emails would be sent to _testmailbox@iris-gateway.de_

2021-07-12 10:50 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +			dataRequestService.sendDataReceivedEmail(updated, patch.getStatus());
This code is not executed, when a data submission arrives. It will be run at updating from frontend (also for CaseData).

2021-07-15 18:16 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +			dataRequestService.sendDataReceivedEmail(updated, patch.getStatus());
I think Timo is right and the appropriate place to send the email would be `EventDataControllerImpl.submitGuestList`.

2021-07-15 18:50 UTC, jekutzsche requested changes
> IMHO we should have a possibility to deactive the email sending (with default deactivated). With the current configuration all emails would be sent to _[testmailbox@iris-gateway.de](mailto:testmailbox@iris-gateway.de)_

I can well understand the thought. If I'm not mistaken, many GAs are also logging a lot of errors at the moment because emailing is not configured. Also therefore a switch would probably be good.

2021-07-15 18:50 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/cases/web/CaseDataRequestController.java
> +		caseDataRequestService.sendDataReceivedEmail(responseEntity.getBody(), update.getStatus());
The appropriate place to send the email would be `CaseDataSubmissionService.validateAndSaveData`.

2021-07-16 05:14 UTC, jekutzsche requested changes

2021-07-16 05:14 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/EventEmailProvider.java
> +			return new AsyncResult<Try<Void>>(sendMail(email, standardRecipientForLogEntries, parameters.get("eventId").toString()));
It was intended that a `TemplatedEmail` represents a complete email. Now the recipient is determined and processed separately. Is there anything against using the recipient data from the `TemplatedEmail` object in `EmailProvider.sendMail` and extending this class with get methods if necessary?

The remark is of course also valid for `CaseEmailProvider.sendDataReceivedEmailAsynchronously`.

2021-07-21 10:08 UTC, jekutzsche requested changes

2021-07-21 10:08 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/core/mail/EmailProvider.java
> +					sendTillSuccessOrLimitReached(email, logArgs, count);
The sending attempts are made immediately one after the other. I think that these can be done too fast if the server is not available. I suggest to add a waiting time here.

2021-07-26 16:14 UTC, SWlionmint reviewed
I have added most improvements. Still am working on the removal of recipient from sendEmail and on checking tests. There might be ones I have to add.

2021-07-27 09:26 UTC, tboegner commented on iris-client-bff/src/main/resources/messages.properties
> +EventDataReceivedEmail.subject=Neue Event Daten sind verfügbar auf dem IRIS Portal
I committed this file again with UTF-8 encoding, so the file is OK.
I suspect my git environment to change encoding when checking out. But you could check, which encoding a new messages file gets, when it is created at your site (just for avoiding errors here).

2021-07-27 09:36 UTC, tboegner commented on iris-client-bff/src/main/resources/application.properties
>  spring.mail.properties.fix-recipient=testmailbox@iris-gateway.de
Unless configured explicitly, the application will fail to start on environments that don't use `application-dev_env.properties`. Therefore it is enforced for server environments.
In my opinion we would need a defined (DevOps-)process for introducing new config parameters, since they should be documented in installation docs and also introduced in our own deployment process.

2021-07-27 10:35 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/events/EventEmailProvider.java
> +			return new AsyncResult<Try<Void>>(sendMail(email, standardRecipientForLogEntries, parameters.get("eventId").toString()));
I have changed it so that it is not needed anymore.

2021-07-27 10:56 UTC, SWlionmint commented on iris-client-bff/src/main/resources/application.properties
>  spring.mail.properties.fix-recipient=testmailbox@iris-gateway.de
I have created a story to follow up on this.
https://github.com/iris-connect/iris-backlog/issues/207

2021-07-27 11:45 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/EventEmailProvider.java
> +		if (dataReceivedRecipientName != null && dataReceivedRecipientEmail != null) {
🤦 Sorry, `dataReceivedRecipientName` is of course not an e-mail address.

2021-07-27 12:24 UTC, jekutzsche commented on iris-client-bff/src/main/resources/application.properties
>  spring.mail.properties.fix-recipient=testmailbox@iris-gateway.de
For custom properties, in a properties class I would declare the field for the property as `@NonNull` and then there is an error if it is not configured. However, here we are dealing with a property from Spring. Here I suggest to add the following method in the class `EmailSender`.

```
	@PostConstruct
	void checkMailProperties() {

		var properties = mailProperties.getProperties();

		Assert.hasText(properties.get("fix-sender-name"),
				"The property fix-sender-name must contains the name of the sender!");
		Assert.hasText(properties.get("fix-sender"),
				"The property fix-sender must contains the e-mail address of the sender!");
		Assert.hasText(properties.get("fix-recipient"),
				"The property fix-recipient must contains the e-mail address of the recipient!");
	}
```

2021-07-28 16:07 UTC, tboegner requested changes
Sending email failed. I tried to configure my private email address for event data updates, but I didn't receive it.

2021-07-28 21:31 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/core/mail/EmailProvider.java
> +	@Value("${spring.mail.properties.limit.resending.delay:30000}")
3 sec for the test and 30 for the runtime are fine, I think.

2021-07-28 21:34 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/core/mail/EmailProvider.java
> +	protected Try<Void> sendMail(TemplatedEmail email, String id) {
Why? The interface should represent a mail and the abstract class should be just a utility for the implementations.

2021-07-28 21:47 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/core/mail/EmailProvider.java
> +			recipient = getConfiguredRecipient(((AbstractTemplatedEmail) email).getTo());
The interface offers the possibility to design the interface more specifically and should be extended here. But I agree with you, here the abstract class should also be sufficient. I would call it `TemplatedEmail`, because the "Abstract" is just ballast, if this type is used in the code.

2021-07-29 13:27 UTC, jekutzsche approved these changes

2021-07-30 07:08 UTC, tboegner commented
Fetching email from test mail server localhost:3993 failed (no severe problem):
Exception in thread "imaps:127.0.0.1:3993<-/127.0.0.1:53206" java.lang.IllegalStateException: Can not handle IMAP connection
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:76)
	at com.icegreen.greenmail.server.AbstractServer.lambda$handleClientSocket$0(AbstractServer.java:160)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Connection or outbound has closed
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1205)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:75)
	... 2 more
Exception in thread "imaps:127.0.0.1:3993<-/127.0.0.1:53208" java.lang.IllegalStateException: Can not handle IMAP connection
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:76)
	at com.icegreen.greenmail.server.AbstractServer.lambda$handleClientSocket$0(AbstractServer.java:160)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Connection or outbound has closed
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1205)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:75)
	... 2 more

2021-07-30 07:13 UTC, tboegner approved these changes
Switch is now integrated and sending is triggered at right place.
Next step is testing on DEV environment to send out emails.

2021-07-30 09:33 UTC, merged