Feature/145 input validation
iris-connect/iris-client pull request #223
Opened 2021-07-22 16:00 UTC by SWlionmint

2021-07-27 09:10 UTC, tboegner requested changes
Some features are not working, e.g. changing name or comment of an event data request.

2021-07-27 09:10 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/core/utils/ValidationHelper.java
> +		if (input.contains("SELECT") && input.contains("FROM"))
The lower case variants are still possible.

2021-07-28 14:41 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/cases/eps/CaseDataControllerImpl.java
> +			log.trace("Start submission {}: contacts = {}; events = {}; dataProvider = {}", dataAuthorizationToken, contacts, events, dataProvider);
Which of the data exactly would you not display. I think the data of who is possibly infected. What do you think?

2021-07-28 14:43 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/cases/eps/CaseDataControllerImpl.java
> +		return true;
I think I actually forgot to finish the implementation here.

2021-07-28 14:45 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/cases/web/CaseDataRequestController.java
> +
generally yes, but they are actually different classes. Even if they have the same or near same structure

2021-07-28 14:48 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/core/utils/ValidationHelper.java
> +			"„" };
No I have no recommendation for this. But the list in question actually only is for the first sign or signs. Basically only a alphanumeric signs are allowed for the first symbol. Do you see anywhere where this would not be correct?

2021-07-28 14:48 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +	private EventUpdateDTO eventUpdateDTOInputValidated(EventUpdateDTO patch) {
good point.

2021-07-29 14:43 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/core/utils/ValidationHelper.java
> +		if (input.contains("SELECT") && input.contains("FROM"))
Is resolved

2021-07-29 14:49 UTC, SWlionmint commented on iris-client-fe/src/views/user-login/user-login.view.vue
> +      defined: [rules.defined, rules.sanitised],
Adjusted

2021-07-29 14:50 UTC, SWlionmint commented on iris-client-fe/src/views/admin-user-edit/admin-user-edit.view.vue
> +      password: [rules.password, rules.sanitised],
corrected now the same

2021-07-29 14:59 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +			|| patch.getStatus() == EventStatusDTO.CLOSED)) {
Fixed

2021-07-29 14:59 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +			|| patch.getStatus() == EventStatusDTO.CLOSED)) {
Also for the CaseDataRequestController case

2021-07-29 15:44 UTC, SWlionmint commented on iris-client-fe/src/utils/sanitisation.ts
> +export const sanitiseAndCheckUIInputWithNoRestrictionToInput = function (
It is a wrapper. While it does not do much right now, I would let it be. I think sanitiseField was once a function not exported.

2021-07-29 15:57 UTC, SWlionmint commented on iris-client-fe/src/common/validation-rules.ts
> +    return "Aus Sicherheitsgründen ist die Sequenz <script nicht erlaubt. Bitte modifiziere deine Eingabe.";
I have changed it to: Bitte modifizieren Sie die Eingabe.

This is more formal. Please check other Displays, those all tend to use direct speech. We should decide on one style we want to use.

2021-07-29 16:04 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +			request.setRequestDetails(ErrorMessages.INVALID_INPUT_STRING);
This has been cleared up, but even in the original it should not have done that. Please test it again and if it still happens we have to check it again. Null should not trigger a true. I am unsure if you meant blank as "" or " ". I am not sure how it would react than.

2021-07-29 16:10 UTC, SWlionmint commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +	private DataRequestClient dataRequestClientInputValidated(DataRequestClient request) {
Should now all be starting with a verb

2021-07-30 07:27 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/cases/eps/CaseDataControllerImpl.java
> +			log.trace("Start submission {}: contacts = {}; events = {}; dataProvider = {}", dataAuthorizationToken, contacts, events, dataProvider);
At least the contacts and events. 
Tokens may be also too sensitive to log, but then we would have nothing anymore. I think there should be another solution allowing the operations team to get these informations, when errors arrise. Should be discussed in team.

2021-08-04 14:26 UTC, tboegner approved these changes

2021-08-04 15:12 UTC, merged