Feature/backlog#160 output sanitization
iris-connect/iris-client pull request #225
Opened 2021-07-23 13:22 UTC by greshake

Improves robustness & documentation of our CSV sanitization. Now uses an explicit whitelist and better documented Regex features that work more predictably in different browsers.

This PR reduces the range of allowed and unfiltered input, so it might conflict with some use cases in the future. In the spirit of defensive programming, we can lift specific restrictions later as they arise.

Discussion: Previous behaviour was to only sanitize the separator symbol used in the output format (either , or ;), but for now I wanted to replace both in either case (independent of the separator parameter)- unsure if this conflicts with any known use cases.

2021-07-23 15:14 UTC, SWlionmint requested changes
Are you sure that this works as a white list in this way? 

Does it not work like this?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

2021-07-23 15:15 UTC, SWlionmint requested changes
Sorry first was not what I wanted to do.

2021-07-23 15:15 UTC, SWlionmint commented on iris-client-fe/src/utils/data-export.ts
> +  field = field.replace(regex_whitelist, "");
Are you sure that this works as a white list in this way?

Does it not work like this?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

2021-07-23 15:30 UTC, greshake commented on iris-client-fe/src/utils/data-export.ts
> +  field = field.replace(regex_whitelist, "");
Yea, it replaces all that matches the regex. The regex matches anything that is *not* in the negated group set/whitelist: a-zA-Z0-9äüöÄÜÖß(): \-@+.;,
You could say that the regex acts as a blacklist, removing anything not in the whitelist. But since we define only the things that do not match specifically, it's a whitelist approach.

2021-07-26 07:49 UTC, SWlionmint commented on iris-client-fe/src/utils/data-export.ts
> +  field = field.replace(regex_whitelist, "");
Okay didn't know that ^negates the set. Super.

2021-07-26 07:50 UTC, SWlionmint approved these changes
Looks good.

2021-07-28 09:17 UTC, merged