fix: bl 233 guestlist validation
iris-connect/iris-client pull request #254
Opened 2021-08-10 15:30 UTC by tboegner

Input validation for guest lists from app providers:

- No format assumptions
- Strings are cutted at max length of DB field
- Attack detection validation for Strings
- New forbidden keyword 
Tested with "naughty" guestlist

2021-08-11 18:34 UTC, jekutzsche requested changes

2021-08-11 18:34 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +		if(validHelper.isPossibleAttack(input, field, obfuscateLogging)) {
I find it inconvenient that the method name does not allow any conclusion about the meaning of the return type. So a look into the code is necessary. I would find clearer as name e.g. `checkAndDefuseInput`. `defuseInput` would perhaps also do.

2021-08-11 18:34 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +			validateGuestList(guestList);
I find `ValidationHelper.isUUIDInputValid` useless, because we already have an object of type `UUID` and therefore a valid UUID.

2021-08-11 18:34 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +		return input;
A hint: This could be replaced by `return StringUtils.truncate(input, maxLength);` from Apache Commons.

2021-08-11 18:34 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +				"dataProvider.name", false, 256));
I would also obfuscate these fields, as the name can also be a personal date (e.g. for private events) and `additionalInformation` can contain anything.

2021-08-11 18:34 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +						"guest.attendanceInformation.descriptionOfPartizipation", false, 500));
I would also obfuscate these fields.

2021-08-12 14:07 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +		if(validHelper.isPossibleAttack(input, field, obfuscateLogging)) {
Changed to `defuseInput`.

2021-08-12 14:08 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +			validateGuestList(guestList);
Removed.

2021-08-12 14:09 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +		return input;
Replaced.

2021-08-12 14:13 UTC, tboegner commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +						"guest.attendanceInformation.descriptionOfPartizipation", false, 500));
All fields are obfuscated now.

2021-08-12 14:26 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
> +		return input;
`truncate` can replace more. I have cleaned that up right away.

2021-08-12 14:26 UTC, jekutzsche approved these changes

2021-08-12 14:29 UTC, merged