fix: The client can reach the productive backend service again. For this purpose, the old environment variable IRIS_LOCATION-SERVICE_ENDPOINT is now taken into account again, which has been replaced by IRIS_BACKEND-SERVICE_ENDPOINT.
iris-connect/iris-client pull request #323
Opened 2021-09-01 16:17 UTC by jekutzsche

2021-09-01 18:50 UTC, lucky-lusa commented on iris-client-bff/src/main/java/iris/client_bff/config/BackendServiceProperties.java
> +	}
Can't we also define a validation? So BFF won't start without one being set?

2021-09-01 18:52 UTC, lucky-lusa commented on iris-client-bff/src/main/java/iris/client_bff/config/BackendServiceProperties.java
> +	@NotBlank
Is this sufficient to prevent BFF start without having set at least one?

2021-09-01 19:56 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/config/BackendServiceProperties.java
> +	@NotBlank
Thank you very much for the critical question. You hit the bull's eye, I was not testing the correct system startup with a JUnit test.

2021-09-01 19:59 UTC, hey-johnnypark requested changes

2021-09-01 19:59 UTC, hey-johnnypark commented on infrastructure/deployment/docker-compose.yml
> +      IRIS_BACKEND-SERVICE_ENDPOINT: ${EPS_LS_NAME}
Did we not agree that we rename the Spring property back to the old naming? If we rename it in the docker.compose file, HDs need to replace that file.

2021-09-01 20:09 UTC, jekutzsche commented on infrastructure/deployment/docker-compose.yml
> +      IRIS_BACKEND-SERVICE_ENDPOINT: ${EPS_LS_NAME}
The HDs do not need to replace that file. As written in Slack, iris.location-service.endpoint is used when iris.backend-service.endpoint is not set. So old docker-compose.yml will work again. But the clean new default is iris.backend-service.endpoint and therefore should be in the templates. This should be a clean migration path.

2021-09-01 20:25 UTC, jekutzsche commented on infrastructure/deployment/docker-compose.yml
> +      IRIS_BACKEND-SERVICE_ENDPOINT: ${EPS_LS_NAME}
Ok, so we'll make it minimal #324 and I'll move the proper cleanup from this PR to develop and the next release.

2021-09-02 05:46 UTC, lucky-lusa approved these changes

2021-09-02 13:21 UTC, jekutzsche commented
Okay, now the PR is adjusted as a clean implementation of the property renaming in the develop branch and can be checked again for the next release.

2021-09-03 06:08 UTC, lucky-lusa approved these changes

2021-09-08 06:40 UTC, merged

2021-09-08 06:40 UTC, lucky-lusa commented
Hallo,

vielen Dank für Ihre Nachricht. Leider bin ich erst wieder am 27. September 2021 persönlich erreichbar. Eingehende E-Mails werden in dieser Zeit nicht weitergeleitet und nicht gelesen.

In dringenden Fällen wenden Sie sich bitte an ***@***.*** oder
***@***.***

Meine Kollegen helfen Ihnen gerne weiter.

Viele Grüße,
 
Tim Lusa
Head of Development 

 
COSYNUS GmbH
Europaplatz 5
DE-64293 Darmstadt

Email:   ***@***.***

Kommunikation verbindet. Wir verbinden die Kommunikation.
www.cosynus.de
 
Sie möchten mehr über SmartMeeting erfahren? Vereinbaren Sie direkt online einen Beratungstermin!

Für alle unsere Angebote, Bestellungen, Lieferungen und Leistungen gelten ausschließlich unsere Allgemeinen Geschäftsbedingungen, die jederzeit unter http://www.cosynus.de/agb abgerufen werden können.

COSYNUS GmbH
Sitz der Gesellschaft ist Darmstadt
Eingetragen beim Amtsgericht Darmstadt HRB-Nr. 5559
Geschäftsführer: Michael Reibold
Merged #323 into develop.

-- 
You are receiving this because your review was requested.
Reply to this email directly or view it on GitHub:
https://github.com/iris-connect/iris-client/pull/323#event-5270061232

2021-11-03 17:16 UTC, jekutzsche commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/iris-connect/iris-client/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: