chore: adds authorization for h2 console
iris-connect/iris-client pull request #495
Opened 2021-11-30 14:43 UTC by jekutzsche

2021-12-02 07:13 UTC, mad-nuts requested changes

2021-12-02 07:13 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/auth/db/DbAuthSecurityAdapter.java
> +			http.headers().frameOptions().disable();
Wollen wir an dieser Stelle lieber `http.headers().frameOptions().sameOrigin();` verwenden? Das würde das Risiko reduzieren, dass innerhalb der DEV Umgebung iframes von anderen Quellen geladen werden.

2021-12-02 07:54 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/auth/db/DbAuthSecurityAdapter.java
> +			http.headers().frameOptions().disable();
Um aufrichtig zu sein, ich habe da nur ein Beispiel übernommen. Danke für die Verbesserung.

2021-12-02 08:27 UTC, mad-nuts approved these changes

2021-12-02 08:29 UTC, merged

2021-12-02 14:59 UTC, jekutzsche commented
:tada: This PR is included in version 1.2.0-rc.4 :tada:

The release is available on [GitHub release](https://github.com/iris-connect/iris-client/releases/tag/v1.2.0-rc.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-14 08:05 UTC, jekutzsche commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/iris-connect/iris-client/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: