fix: Error messages are not included in error responses now to avoid …
iris-connect/iris-client pull request #560
Opened 2022-01-07 15:45 UTC by jekutzsche

…giving too many internal details to the outside world for error conditions.

Error messages are included for dev_env profile and for Compose environment dev via overwritten properties/env variables.

@lucky-lusa @mad-nuts 
I think it is a mistake if we generally send the messages along and would therefore change this. The question is whether the error handling or error output in the frontend relies on the message.

2022-01-10 10:35 UTC, lucky-lusa approved these changes

2022-01-17 10:17 UTC, mad-nuts requested changes
Wir geben im Frontend die message property aus. Diese Ausgabe ist in der Regel auch hilfreich / sinnvoll da sie Aufschluss über den Grund des Fehlers gibt und bereits in Klartext formatiert ist. - z.B.: "Fehler: Ereignisortsuche fehlgeschlagen." usw. Mein Vorschlag wäre es, die message property beizubehalten und im "GlobalControllerExceptionHandler" für alle nicht behandelten Fehler eine generische Message auszugeben (handleException müsste das sein, glaube ich). Damit der Stacktrace nicht ans Frontend übergeben wird, würde ich folgende config setzen: "server.error.include-stacktrace=never"

2022-01-17 13:53 UTC, jekutzsche commented
> Damit der Stacktrace nicht ans Frontend übergeben wird, würde ich folgende config setzen: "server.error.include-stacktrace=never"

Ja, ich halte das auch für eine sehr gute Idee. Für Dev lokal in der IDE würde ich es explizit aktivieren.

> Mein Vorschlag wäre es, die message property beizubehalten und im "GlobalControllerExceptionHandler" für alle nicht behandelten Fehler eine generische Message auszugeben (handleException müsste das sein, glaube ich).

Ok, das habe ich nicht beachtet und sollte in der Tat bleiben. Ich würde dann allerdings im Moment `message` lassen wie es ist, da wir wahrscheinlich bei vielen Exceptions sinnvolle in `message` schreiben.

2022-01-18 08:48 UTC, mad-nuts approved these changes

2022-01-18 09:35 UTC, merged

2022-02-01 10:04 UTC, jekutzsche commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/iris-connect/iris-client/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: