Feat/ga messenger payload
iris-connect/iris-client pull request #640
Opened 2022-02-28 16:06 UTC by mad-nuts

2022-03-16 16:29 UTC, jekutzsche requested changes
The DB scripts are not yet correct, because the DB tests fail during the build.

I'm not finished yet, but would like to give some feedback in between.

2022-03-16 16:29 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/web/IrisMessageController.java
> +			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, messages.getMessage("iris_message.invalid_message_data") + ": "+ field);
You can use `messages.getMessage("iris_message.invalid_message_data", field)` with `iris_message.invalid_message_data=…: {0}` to avoid string concatenation.

2022-03-18 09:40 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/IrisMessageDataProcessors.java
> +	}
The IrisMessageDataProcessors` constructor is autowired itself (line 33), "auto injecting" the IrisMessageDataProcessor list.

The IrisMessageDataProcessor is the interface for all MessageDataProcessor "types", e.g. the EventMessageDataProcessor.

2022-03-18 09:45 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/IrisMessageDataProcessors.java
> +		} catch (Throwable e) {
Shouldn't be an issue in this case as the error (message) is not used / processed.
But good to know, thanks! I'll change the Throwables to Exceptions.

2022-03-18 09:58 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/EventMessageDataPayload.java
> +					.filter((guest -> guestIds.size() <= 0 || guestIds.contains(guest.getGuestId().toString())))
will be changed, thanks

2022-03-18 10:00 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/EventMessageDataPayload.java
> +					}).collect(Collectors.toList());
will be changed, thanks

2022-03-18 10:02 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/web/IrisMessageInsertDto.java
> +    private List<DataAttachment> dataAttachments;
will be changed, thanks

2022-03-18 10:06 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/IrisMessageDataProcessors.java
> +		} catch (Throwable e) {
Here in the example there will be no problem, but for clarification a few words. The problem is not the usage of the error or message, but the control flow. If there is an `OutOfMemoryError` in the `try{...}`, then it will be caught with `Throwable` too. But there is no meaningful handling without memory (throwing another exception), the application is dead.

2022-03-18 10:06 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/web/IrisMessageController.java
> +			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, messages.getMessage("iris_message.invalid_message_data") + ": "+ field);
removed the field part as it is not really necessary

2022-03-18 10:09 UTC, mad-nuts commented on iris-client-bff/src/main/resources/db/migration/V1012__add_iris_message_data.sql
> +    payload varchar(999999) NOT NULL,
will be changed to text

2022-03-18 10:12 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/IrisMessageDataProcessors.java
> +	}
I think, that passing all dependencies into the constructor would make the idea behind the code harder to understand. But sure, I'll change it.

2022-03-18 10:36 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/EventMessageDataPayload.java
> +		private String refId;
The refId is a required field in the EventDataRequest builder. I set the import value to "-" and exclude the refId from the payload.

2022-03-18 10:57 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/utils/RawJsonDeserializer.java
> +}
ok

2022-03-18 13:14 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/events/message/EventMessageDataPayload.java
> +		private String refId;
`-` at the beginning is one of the forbidden characters. Not that we get then a 400, e.g. with an update. Maybe rather a text like "nicht vergeben - wurde importiert" with I18N?

2022-03-18 13:26 UTC, jekutzsche commented on iris-client-bff/src/main/java/iris/client_bff/iris_messages/IrisMessageDataProcessors.java
> +	}
Also now you have to look at the code to understand what is done there. It would be generally useful for understanding to give it a name and to outsource this code to a function (e.g. `extractDiscriminatorProcessorMap`).

2022-03-21 08:53 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/EventMessageDataPayload.java
> +		private String refId;
Good idea! Thanks!

2022-03-21 09:54 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/dto/ExportSelectionDto.java
> +			ObjectMapper objectMapper = new ObjectMapper();
I'll change it to the default ObjectMapper

2022-03-21 09:54 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/dto/ImportSelectionDto.java
> +			ObjectMapper objectMapper = new ObjectMapper();
I'll change it to the default ObjectMapper

2022-03-21 11:04 UTC, mad-nuts commented on iris-client-bff/src/main/java/iris/client_bff/events/message/EventMessageDataPayloadDefuse.java
> +import iris.client_bff.events.eps.EventDataDefuse;
I'll move it

2022-04-05 08:25 UTC, jekutzsche approved these changes

2022-04-05 08:52 UTC, merged

2022-06-30 15:01 UTC, jekutzsche commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on [GitHub release](https://github.com/iris-connect/iris-client/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: