feat: ui improvements to the event tracking creation
iris-connect/iris-client pull request #81
Opened 2021-05-14 13:18 UTC by SWlionmint

I have changed the Date Format to german, made date and time configurable via Keyboard after entering it via tabulartor and added a Alert message when a new request is made. Works for both Events and Indexcases.

2021-05-21 13:32 UTC, bianucci commented on iris-client-fe/src/components/alerts/alert.component.vue
> +      :value="alert"
Do we need this value?

2021-05-21 13:36 UTC, bianucci commented on iris-client-fe/src/views/event-tracking-details/components/event-tracking-details.component.vue
> +  alert = false;
This seems to be unused?

2021-05-21 13:39 UTC, bianucci commented on iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue
> +                query: { is_created: 'false' },
Do we need to pass the query object?

2021-05-21 13:41 UTC, bianucci commented on iris-client-fe/src/views/index-tracking-details/index-tracking-details.view.vue
> +    this.$router.replace({ query });
I guess the query param should be reset immediately after it has been used, in `created`

2021-05-21 13:41 UTC, bianucci commented on iris-client-fe/src/views/index-tracking-list/index-tracking-list.view.vue
> +                query: { is_created: 'false' },
do we need to pass the query object?

2021-05-21 13:45 UTC, bianucci requested changes
see comments

2021-05-21 15:40 UTC, SWlionmint commented on iris-client-fe/src/components/alerts/alert.component.vue
> +      :value="alert"
Removed

2021-05-21 15:41 UTC, SWlionmint commented on iris-client-fe/src/views/event-tracking-details/components/event-tracking-details.component.vue
> +  alert = false;
Removed

2021-05-21 15:48 UTC, SWlionmint commented on iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue
> +                query: { is_created: 'false' },
Removed and added a catch to prevent error in console

2021-05-21 15:48 UTC, SWlionmint commented on iris-client-fe/src/views/index-tracking-list/index-tracking-list.view.vue
> +                query: { is_created: 'false' },
Removed and added a catch to prevent error in console

2021-05-21 15:51 UTC, SWlionmint commented on iris-client-fe/src/views/index-tracking-details/index-tracking-details.view.vue
> +    this.$router.replace({ query });
I have adjusted this. It was previously needed when the logic was still in the component and not the view.

2021-05-21 15:53 UTC, SWlionmint commented
@bianucci I have made the changes.

2021-05-22 14:50 UTC, bianucci approved these changes
see comments

2021-05-25 12:41 UTC, bianucci submitted a review, later dismissed

2021-05-25 15:43 UTC, bianucci approved these changes

2021-05-25 15:49 UTC, merged