feat: pagination for index cases and events lists
iris-connect/iris-client pull request #84
Opened 2021-05-19 07:17 UTC by faversente

BREAKING CHANGE: 

This PR introduces API driven pagination (+ sort, search and filter) for "getAll" functionality in index cases and events lists.

2021-05-22 09:01 UTC, faversente commented
All proposed and discussed changes should be implemented now.
@bianucci please re-review.

2021-05-23 08:50 UTC, bianucci commented on iris-client-bff/src/main/java/iris/client_bff/cases/web/IndexCaseController.java
> +		else if (search != null) {
Lets use `StringUtils.isNotEmpty`

2021-05-23 08:52 UTC, bianucci commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +		} else if (search != null) {
Same here: lets use StringUtils

2021-05-23 08:56 UTC, bianucci commented on iris-client-bff/src/test/java/iris/client_bff/events/web/EventDataRequestControllerIntegrationTest.java
> +				new EventDataRequest(
Let's use the Builder API.

2021-05-23 09:06 UTC, bianucci commented on iris-client-fe/src/api/common.ts
> +export interface DataPage<T> {
I think this type should not be defined here. Consumers should use `PageIndexCase` or `PageEvent`.

Lets discuss this directly.

2021-05-23 09:10 UTC, bianucci commented on iris-client-fe/src/utils/misc.ts
> +export function getStringParamFromRouteWithOptionalFallback(
Lets introduce a `Pagination.ts` utils module for this code.

2021-05-23 09:13 UTC, bianucci commented on iris-client-fe/src/constants/QueryParams.ts
> +export const QueryParamName = {
Suggestion: 
1. rename file to: url-query-params.ts
2. rename const to PaginationQueryParams

2021-05-23 09:15 UTC, bianucci commented on iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue
> +          label="Suche (min. 2 Buchstaben)"
Suggestion: `Suchbegriff (min. 2 Buchstaben)"

2021-05-23 09:18 UTC, bianucci commented on iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue
> +          :footer-props="{ 'items-per-page-options': [5, 10, 15] }"
Wondering: `5, 10, 15` are specified requirements or is it more of a good guess?
Maybe `10, 20, 30, 50` would be more helpful to users?

2021-05-23 09:21 UTC, bianucci commented on iris-client-fe/src/views/index-tracking-list/index-tracking-list.view.vue
> +  statusButtonSelected = this.statusFilter
Lets make this a computed attribute to improve readability.

2021-05-23 09:29 UTC, bianucci commented on iris-client-fe/src/views/index-tracking-list/index-tracking-list.view.vue
> +          label="Suche (min. 2 Buchstaben)"
Suggestion: rename to `Suchbegriff (...`

2021-05-23 09:31 UTC, bianucci commented on iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue
> +  headers = [
I guess `headers` should be part of dataTableOptions.

```
dataTableOptions = {
  currentPage: getPageFromRouteWithDefault(this.$route),
  itemsPerPage: getPageSizeFromRouteWithDefault(this.$route),
  headers: [
````

No strong feelings though

2021-05-23 09:32 UTC, bianucci requested changes
see comments

2021-05-24 07:45 UTC, faversente commented on iris-client-bff/src/main/java/iris/client_bff/cases/web/IndexCaseController.java
> +		else if (search != null) {
Done for `search`. `status` is an Enum

2021-05-24 07:45 UTC, faversente commented on iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
> +		} else if (search != null) {
Done for `search`. `status` is an Enum

2021-05-24 08:25 UTC, faversente commented on iris-client-fe/src/constants/QueryParams.ts
> +export const QueryParamName = {
was not used anymore, deleted

2021-05-24 08:29 UTC, faversente commented on iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue
> +          :footer-props="{ 'items-per-page-options': [5, 10, 15] }"
`5, 10, 15, All` are the default values in `v-data-table`. I also think `10, 20, 30, 50` are probably more useful and have changed them accordingly

2021-05-24 08:44 UTC, faversente commented on iris-client-fe/src/api/common.ts
> +export interface DataPage<T> {
This interface is currently only used within the event/index-case lists, and acts as a mapper from PageIndexCase/PageEvent => TableRow specified for table data visualization.

Maybe it is sufficient to move and rename it?

2021-05-25 10:30 UTC, bianucci approved these changes

2021-05-25 10:56 UTC, merged